#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

load_app_settings

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backing up the main app directory..."

# remove some extra files
ynh_secure_remove "$final_path/readme"
ynh_secure_remove "$final_path/documentation"
ynh_secure_remove "$final_path/container"
ynh_secure_remove "$final_path/app"
ynh_secure_remove "$final_path/api/vendor"
ynh_secure_remove "$final_path/api/.composer"

ynh_backup --src_path="$final_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Backing up nginx web server configuration..."

ynh_backup --src_path="$nginx_config_path"

#=================================================
# BACKUP THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Backing up php-fpm configuration..."

ynh_backup --src_path="$php_fpm_config_path"

#=================================================
# BACKUP FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression --message="Backing up fail2ban configuration..."

ynh_backup --src_path="$fail2ban_jail_path"
ynh_backup --src_path="$fail2ban_filter_path"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)." --last
