#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH

new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# LOAD SETTINGS
#=================================================

load_app_settings

new_path_url="$(ynh_normalize_url_path --path_url=$new_path_url)"
new_normalized_path_url="$(str_remove_leading "$new_path_url" '\/')"

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================

change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
    change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
    change_path=1
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating nginx web server configuration..." --time --weight=1

# Change the path in the nginx config file
if [ $change_path -eq 1 ]
then
    # Make a backup of the original nginx config file if modified
    ynh_backup_if_checksum_is_different --file="$nginx_conf_path"
    # Set global variables for nginx helper
    domain="$old_domain"
    path_url="$new_path"
    # Create a dedicated nginx config
    ynh_add_nginx_config
fi

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
    # Delete file checksum for the old conf file location
    ynh_delete_file_checksum --file="$nginx_conf_path"
    mv "$nginx_conf_path" "/etc/nginx/conf.d/$new_domain.d/$app.conf"
    # Store file checksum for the new config file location
    ynh_store_file_checksum --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
fi

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

if [ $change_domain -eq 1 ]
then
  # set the domain
  ynh_replace_string \
      --match_string="DOMAIN=\"\[^\"\]*\"" \
      --replace_string="DOMAIN=\"$new_domain\"" \
      --target_file="$final_path/data/config"
fi

if [ $change_path -eq 1 ]
then
  # set the PATH of the webapp
  ynh_replace_string \
      --match_string="<base href=\"/\">" \
      --replace_string="<base href=\"/$new_normalized_path_url/\">" \
      --target_file="$final_path/public/index.html"
fi

#=================================================
# GENERIC FINALISATION
#=================================================

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..." --time --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --time --last
